# Generated by Django 2.1.7 on 2019-03-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=200)),
                ('UPC', models.CharField(max_length=200)),
                ('Product_Name', models.CharField(max_length=200)),
                ('Food_Group', models.CharField(max_length=200)),
                ('Calories', models.DecimalField(max_digits=50, decimal_places=5)),
                ('Total_Carbohydrates', models.DecimalField(max_digits=50, decimal_places=5)),
                ('Protein', models.DecimalField( max_digits=50, decimal_places=5)),
                ('Total_Fat', models.DecimalField(max_digits=50, decimal_places=5)),
                ('Sodium', models.DecimalField(max_digits=50, decimal_places=5)),
                ('Cholesterol', models.DecimalField(max_digits=50, decimal_places=5)),
                ('Sugars', models.DecimalField(max_digits=50, decimal_places=5)),
            ],
        ),
    ]
