# Generated by Django 2.1.7 on 2019-03-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='ID',
            new_name='Food_ID',
        ),
        migrations.AlterField(
            model_name='sample',
            name='Calories',
            field=models.DecimalField(decimal_places=5, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Cholesterol',
            field=models.DecimalField(decimal_places=5, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Protein',
            field=models.DecimalField(decimal_places=5, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Sodium',
            field=models.DecimalField(decimal_places=5, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Sugars',
            field=models.DecimalField(decimal_places=5, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Total_Carbohydrates',
            field=models.DecimalField(decimal_places=5, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Total_Fat',
            field=models.DecimalField(decimal_places=5, max_digits=10000),
        ),
    ]
